### ISSUE TITLE
Import “ImportObject” from python “wasmer” doesn't work for 0.4.1

### ISSUE THREAD

**Issue by joker512-tmp** [wasmerio/python-ext-wasm#215]
I posted it as a question here and on stackOverflow, and nobody answered, so now it's clear it's a bug.

    pip install wasmer
    python -c 'from wasmer import ImportObject'
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
    ImportError: cannot import name 'ImportObject' from 'wasmer' (/usr/lib/python3.8/site-packages/wasmer.cpython-38-x86_64-linux-gnu.so
"ImportObject" class is described in [readme][1] and presented in [examples][2]. I've checked that proper 0.4.1 version of "wasmer" was installed. Also I checked the newest tagged [version][3] of "wasmer" which fails with the same error. What can be wrong?

generate_import_object() function doesn't work also:

    python -c "from wasmer import Module; Module.generate_import_object()"
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
    AttributeError: type object 'Module' has no attribute 'generate_import_object'
This code gives the same result:

    wasm_bytes = open('binary.wasm', 'rb').read()
    module = Module(wasm_bytes)
    import_object = module.generate_import_object()

  [1]: https://github.com/wasmerio/python-ext-wasm#the-importobject-class
  [2]: https://github.com/wasmerio/python-ext-wasm/blob/master/examples/imported_function.py#L1
  [3]: https://github.com/wasmerio/python-ext-wasm/releases/tag/0.4.2-beta.11

**Comment by joker512-tmp** [comment]
Con

**Comment by Hywan** [comment]
Can you check the output of `Features.host_functions()` please? Maybe host functions aren't supported on your platform (https://github.com/wasmerio/python-ext-wasm/blob/master/src/features.rs#L13-L19).

**Comment by joker512-tmp** [comment]
```
python -c "from wasmer import Features; Features.host_functions()"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: cannot import name 'Features' from 'wasmer' (/usr/lib/python3.8/site-packages/wasmer.cpython-38-x86_64-linux-gnu.so)
```
If I understand you correctly…

**Comment by Hywan** [comment]
Wasmer 0.4.1 has been released on March 2nd.
The `ImportObject` API has been merged on June 2nd (#167).

So it's not part of the 0.4.1 released. A new release is coming in a couple of weeks. Alternatively, you can build your own wheels with `just build && just wheels …`. Alternatively, you can use the beta release, https://github.com/wasmerio/python-ext-wasm/releases/tag/0.4.2-beta.11.

**Comment by joker512-tmp** [comment]
I use 0.4.2-beta.11 version for tests:
```
python -c "import wasmer; print(wasmer.__version__)"
0.4.2-beta-11
```
And [0.4.2-beta.11](https://github.com/wasmerio/python-ext-wasm/releases/tag/0.4.2-beta.11) was released on May, 19, before June, 2. So, it looks that it missed there too.

**Comment by Hywan** [comment]
Ah true, yes, it's missing from the beta. Can you wait for a couple of weeks please?

**Comment by joker512-tmp** [comment]
> Ah true, yes, it's missing from the beta. Can you wait for a couple of weeks please?
I can try to build it by myself in this case.
```
just build
Build arguments:
    Finished dev [unoptimized + debuginfo] target(s) in 0.06s
💥 maturin failed
  Caused by: You need to be inside a virtualenv or conda environment to use develop (neither VIRTUAL_ENV nor CONDA_PREFIX are set)
```
Does it mean I just need to install conda to build it?

**Comment by joker512-tmp** [comment]
Resolved by creating virtualenv (strange requirement, but anyway).

**Comment by joker512-tmp** [comment]
Another problem I have – what "rust_target" should be [here](https://github.com/wasmerio/python-ext-wasm/blob/master/justfile#L71)? Sorry, I didn't work with Rust lang before. Now I get:

```
just build-wheel 0.4.3 1.45.2
Build arguments:
💥 maturin failed
  Caused by: Unknown target triple 1.45.2
error: Recipe `build-wheel` failed with exit code 1
```

**Comment by joker512-tmp** [comment]
Answer my own question. The build command: `just build-wheel python x86_64-unknown-linux-gnu`, – for usual linux and python. Moreover you need to install wheel package manually: `pip install wheel`. After installing whl build the problem seems to be fixed.
